In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
from pathlib import Path 
data_path = Path("../data/transactions.csv")
data_path.exists()

True

In [7]:
df=pd.read_csv(data_path)
df.head()

,transaction_id,user_id,receiver_id,receiver_type,amount,timestamp,date,hour_of_day,day_of_week,is_weekend,...,user_loyalty_score,new_device_flag,ip_location_mismatch,failed_attempts_last_24h,transaction_velocity,amount_deviation_score,is_fraud,recurring_payment_flag,balance_after_transaction,transaction_frequency_score
0,TXN0013171,USR01949,MRC0069,Merchant,1533.88,2024-01-01 00:21:17,2024-01-01,0,Monday,0,...,0.194,0,0,2,0.0,2.2467,0,1,36023.96,0.72
1,TXN0006480,USR01975,MRC0048,Merchant,1371.57,2024-01-01 00:36:29,2024-01-01,0,Monday,0,...,0.213,0,0,0,4.0,1.1773,0,0,65138.89,0.68
2,TXN0001430,USR01127,MRC0312,Merchant,500.50,2024-01-01 00:47:46,2024-01-01,0,Monday,0,...,0.381,0,0,0,1.0,0.1471,0,1,69347.11,0.86
3,TXN0003501,USR00827,USR01877,User,724.05,2024-01-01 00:52:07,2024-01-01,0,Monday,0,...,0.238,0,0,1,0.0,1.6019,0,0,52305.43,1.00
4,TXN0004423,USR00673,USR00534,User,128.22,2024-01-01 01:22:31,2024-01-01,1,Monday,0,...,0.187,0,0,5,1.0,0.3076,0,0,9601.13,0.48

In [8]:
df.shape

(20000, 30)

In [9]:
df.columns

Index(['transaction_id', 'user_id', 'receiver_id', 'receiver_type', 'amount',
       'timestamp', 'date', 'hour_of_day', 'day_of_week', 'is_weekend',
       'is_night_transaction', 'time_since_last_txn_min', 'transaction_type',
       'payment_app', 'device_type', 'status', 'user_city_tier',
       'user_kyc_status', 'user_avg_monthly_txn', 'user_avg_txn_value',
       'user_loyalty_score', 'new_device_flag', 'ip_location_mismatch',
       'failed_attempts_last_24h', 'transaction_velocity',
       'amount_deviation_score', 'is_fraud', 'recurring_payment_flag',
       'balance_after_transaction', 'transaction_frequency_score'],
      dtype='str')

In [10]:
df.columns.tolist()

['transaction_id',
 'user_id',
 'receiver_id',
 'receiver_type',
 'amount',
 'timestamp',
 'date',
 'hour_of_day',
 'day_of_week',
 'is_weekend',
 'is_night_transaction',
 'time_since_last_txn_min',
 'transaction_type',
 'payment_app',
 'device_type',
 'status',
 'user_city_tier',
 'user_kyc_status',
 'user_avg_monthly_txn',
 'user_avg_txn_value',
 'user_loyalty_score',
 'new_device_flag',
 'ip_location_mismatch',
 'failed_attempts_last_24h',
 'transaction_velocity',
 'amount_deviation_score',
 'is_fraud',
 'recurring_payment_flag',
 'balance_after_transaction',
 'transaction_frequency_score']

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   transaction_id               20000 non-null  str
 1   user_id                      20000 non-null  str
 2   receiver_id                  20000 non-null  str
 3   receiver_type                20000 non-null  str
 4   amount                       20000 non-null  float64
 5   timestamp                    20000 non-null  str
 6   date                         20000 non-null  str
 7   hour_of_day                  20000 non-null  int64
 8   day_of_week                  20000 non-null  str
 9   is_weekend                   20000 non-null  int64
 10  is_night_transaction         20000 non-null  int64
 11  time_since_last_txn_min      17665 non-null  float64
 12  transaction_type             20000 non-null  str
 13  payment_app                  20000 non-null  str
 14  device_type                  20000 non-null  str
 15  status                       20000 non-null  str
 16  user_city_tier               20000 non-null  str
 17  user_kyc_status              20000 non-null  str
 18  user_avg_monthly_txn         20000 non-null  int64
 19  user_avg_txn_value           20000 non-null  float64
 20  user_loyalty_score           20000 non-null  float64
 21  new_device_flag              20000 non-null  int64
 22  ip_location_mismatch         20000 non-null  int64
 23  failed_attempts_last_24h     20000 non-null  int64
 24  transaction_velocity         19607 non-null  float64
 25  amount_deviation_score       19633 non-null  float64
 26  is_fraud                     20000 non-null  int64
 27  recurring_payment_flag       20000 non-null  int64
 28  balance_after_transaction    20000 non-null  float64
 29  transaction_frequency_score  20000 non-null  float64
dtypes: float64(8), int64(9), str(13)
memory usage: 4.6 MB

In [12]:
df.isnull().sum()

transaction_id                    0
user_id                           0
receiver_id                       0
receiver_type                     0
amount                            0
timestamp                         0
date                              0
hour_of_day                       0
day_of_week                       0
is_weekend                        0
is_night_transaction              0
time_since_last_txn_min        2335
transaction_type                  0
payment_app                       0
device_type                       0
status                            0
user_city_tier                    0
user_kyc_status                   0
user_avg_monthly_txn              0
user_avg_txn_value                0
user_loyalty_score                0
new_device_flag                   0
ip_location_mismatch              0
failed_attempts_last_24h          0
transaction_velocity            393
amount_deviation_score          367
is_fraud                          0
recurring_payment_flag            0
balance_after_transaction         0
transaction_frequency_score       0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.tail(10)

,transaction_id,user_id,receiver_id,receiver_type,amount,timestamp,date,hour_of_day,day_of_week,is_weekend,...,user_loyalty_score,new_device_flag,ip_location_mismatch,failed_attempts_last_24h,transaction_velocity,amount_deviation_score,is_fraud,recurring_payment_flag,balance_after_transaction,transaction_frequency_score
19990,TXN0004985,USR01181,USR01970,User,1243.58,2024-12-30 17:44:43,2024-12-30,17,Monday,0,...,0.353,0,0,0,0.0,NaN,0,0,6440.06,0.82
19991,TXN0011710,USR01187,MRC0231,Merchant,1510.30,2024-12-30 17:49:25,2024-12-30,17,Monday,0,...,0.761,0,0,0,0.0,0.7296,0,0,5427.80,0.54
19992,TXN0001488,USR00448,MRC0105,Merchant,357.23,2024-12-30 18:17:24,2024-12-30,18,Monday,0,...,0.397,0,0,0,3.0,0.4392,0,0,32443.82,0.74
19993,TXN0003960,USR00786,MRC0080,Merchant,49.76,2024-12-30 19:11:48,2024-12-30,19,Monday,0,...,0.745,0,1,3,0.0,0.7453,0,0,61843.03,0.70
19994,TXN0018357,USR00088,MRC0146,Merchant,205.17,2024-12-30 20:35:35,2024-12-30,20,Monday,0,...,0.292,0,0,0,4.0,0.3199,0,0,18263.66,0.54
19995,TXN0018270,USR00228,USR01463,User,70.26,2024-12-30 21:59:07,2024-12-30,21,Monday,0,...,0.114,0,0,2,1.0,0.4476,1,0,63553.01,0.46
19996,TXN0006448,USR01360,MRC0360,Merchant,414.20,2024-12-30 22:08:44,2024-12-30,22,Monday,0,...,0.781,1,0,0,1.0,0.3339,0,1,43470.82,1.00
19997,TXN0013837,USR00582,USR00308,User,63.32,2024-12-30 22:09:27,2024-12-30,22,Monday,0,...,0.855,0,0,0,0.0,0.7540,0,0,62472.32,0.60
19998,TXN0009361,USR00557,MRC0317,Merchant,193.06,2024-12-30 22:22:16,2024-12-30,22,Monday,0,...,0.513,0,0,0,2.0,0.0534,0,1,40969.58,0.50
19999,TXN0017978,USR01600,MRC0120,Merchant,7019.75,2024-12-30 22:31:52,2024-12-30,22,Monday,0,...,0.783,0,0,2,0.0,2.9426,0,0,26613.04,1.00

In [17]:
df.describe()

,amount,hour_of_day,is_weekend,is_night_transaction,time_since_last_txn_min,user_avg_monthly_txn,user_avg_txn_value,user_loyalty_score,new_device_flag,ip_location_mismatch,failed_attempts_last_24h,transaction_velocity,amount_deviation_score,is_fraud,recurring_payment_flag,balance_after_transaction,transaction_frequency_score
count,20000.000000,20000.000000,20000.000000,20000.000000,17665.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,19607.000000,19633.000000,20000.000000,20000.00000,20000.000000,20000.000000
mean,876.846854,11.565050,0.281400,0.324600,-899.133724,31.939000,691.624428,0.56031,0.064800,0.038450,0.537250,0.547101,0.653635,0.038150,0.30210,40413.740082,0.615067
std,1083.900556,6.867629,0.449693,0.468237,214733.190266,14.645696,517.225583,0.25846,0.246179,0.192285,1.040705,0.999292,0.789019,0.191563,0.45918,22915.172130,0.246966
min,13.700000,0.000000,0.000000,0.000000,-517802.170000,1.000000,52.280000,0.10100,0.000000,0.000000,0.000000,0.000000,0.000100,0.000000,0.00000,500.750000,0.020000
25%,277.672500,6.000000,0.000000,0.000000,-154683.080000,21.000000,332.470000,0.33000,0.000000,0.000000,0.000000,0.000000,0.221500,0.000000,0.00000,20328.310000,0.420000
50%,539.955000,12.000000,0.000000,0.000000,-1724.130000,30.000000,544.550000,0.56900,0.000000,0.000000,0.000000,0.000000,0.444500,0.000000,0.00000,40398.730000,0.600000
75%,1061.510000,17.000000,1.000000,1.000000,153152.770000,40.000000,904.770000,0.78000,0.000000,0.000000,1.000000,1.000000,0.727600,0.000000,1.00000,60474.840000,0.800000
max,32259.720000,23.000000,1.000000,1.000000,524477.870000,84.000000,4539.450000,1.00000,1.000000,1.000000,5.000000,4.000000,11.359200,1.000000,1.00000,79997.750000,1.000000

In [18]:
df_clean = df.copy()

In [19]:
duplicate_rows=df_clean.duplicated().sum()
duplicate_rows

np.int64(0)

In [21]:
duplicate_transaction_ids=df_clean['transaction_id'].duplicated().sum()
duplicate_transaction_ids

np.int64(0)

In [22]:
categorical_columns = [ 
    'receiver_type',
    'day_of_week',
    'transaction_type',
    'payment_app',
    'device_type',
    'status',
    'user_city_tier',
    'user_kyc_status'
]

for column in categorical_columns:
    print(f"\n{column}:")
    print(df_clean[column].value_counts())

receiver_type:
receiver_type
Merchant    15119
User         4881
Name: count, dtype: int64

day_of_week:
day_of_week
Monday       3016
Friday       2918
Tuesday      2853
Saturday     2827
Wednesday    2813
Sunday       2801
Thursday     2772
Name: count, dtype: int64

transaction_type:
transaction_type
P2M             7014
P2P             4881
Bill Payment    3033
Recharge        2063
EMI             1628
Subscription    1381
Name: count, dtype: int64

payment_app:
payment_app
GPay            6438
PhonePe         5864
Paytm           3738
BHIM            1595
Amazon Pay      1584
WhatsApp Pay     781
Name: count, dtype: int64

device_type:
device_type
Android    13057
iOS         5405
Web         1538
Name: count, dtype: int64

status:
status
Success    17628
Failed      1815
Pending      557
Name: count, dtype: int64

user_city_tier:
user_city_tier
Tier 2    8015
Tier 1    7161
Tier 3    4824
Name: count, dtype: int64

user_kyc_status:
user_kyc_status
Verified        17294
Not Verified     2706
Name: count, dtype: int64

In [23]:
numeric_columns = [
    'amount',
    'time_since_last_txn_min',
    'user_avg_monthly_txn',
    'user_avg_txn_value',
    'user_loyalty_score',
    'failed_attempts_last_24h',
    'transaction_velocity',
    'amount_deviation_score',
    'balance_after_transaction',
    'transaction_frequency_score'
]

df_clean[numeric_columns].describe()

,amount,time_since_last_txn_min,user_avg_monthly_txn,user_avg_txn_value,user_loyalty_score,failed_attempts_last_24h,transaction_velocity,amount_deviation_score,balance_after_transaction,transaction_frequency_score
count,20000.000000,17665.000000,20000.000000,20000.000000,20000.00000,20000.000000,19607.000000,19633.000000,20000.000000,20000.000000
mean,876.846854,-899.133724,31.939000,691.624428,0.56031,0.537250,0.547101,0.653635,40413.740082,0.615067
std,1083.900556,214733.190266,14.645696,517.225583,0.25846,1.040705,0.999292,0.789019,22915.172130,0.246966
min,13.700000,-517802.170000,1.000000,52.280000,0.10100,0.000000,0.000000,0.000100,500.750000,0.020000
25%,277.672500,-154683.080000,21.000000,332.470000,0.33000,0.000000,0.000000,0.221500,20328.310000,0.420000
50%,539.955000,-1724.130000,30.000000,544.550000,0.56900,0.000000,0.000000,0.444500,40398.730000,0.600000
75%,1061.510000,153152.770000,40.000000,904.770000,0.78000,1.000000,1.000000,0.727600,60474.840000,0.800000
max,32259.720000,524477.870000,84.000000,4539.450000,1.00000,5.000000,4.000000,11.359200,79997.750000,1.000000

In [24]:
df_clean['timestamp'] = pd.to_datetime(df_clean['timestamp'])
df_clean['date'] = pd.to_datetime(df_clean['date'])

print("Minimum timestamp:", df_clean['timestamp'].min())
print("Maximum timestamp:", df_clean['timestamp'].max())
print("Minimum date:", df_clean['date'].min())
print("Maximum date:", df_clean['date'].max())

Minimum timestamp: 2024-01-01 00:21:17
Maximum timestamp: 2024-12-30 22:31:52
Minimum date: 2024-01-01 00:00:00
Maximum date: 2024-12-30 00:00:00

In [25]:
invalid_amounts = df_clean[df_clean['amount'] <0]
invalid_amounts.shape

(0, 30)

In [26]:
invalid_hours = df_clean[(df_clean['hour_of_day'] <0) | (df_clean['hour_of_day']>23)]
invalid_hours.shape

(0, 30)

In [27]:
df_clean['is_fraud'].value_counts()

is_fraud
0    19237
1      763
Name: count, dtype: int64

In [28]:
df_clean['is_fraud'].value_counts(normalize=True) * 100

is_fraud
0    96.185
1     3.815
Name: proportion, dtype: float64

In [29]:
df_clean=df.copy()

In [30]:
df_clean['timestamp'] = pd.to_datetime(df_clean['timestamp'])
df_clean['date'] = pd.to_datetime(df_clean['date'])

In [31]:
text_columns = [
    'receiver_type',
    'day_of_week',
    'transaction_type',
    'payment_app',
    'device_type',
    'status',
    'user_city_tier',
    'user_kyc_status'
]

for column in text_columns:
    df_clean[column] = df_clean[column].str.strip()

In [32]:
df_clean['time_since_last_txn_missing'] = df_clean['time_since_last_txn_min'].isnull().astype(int)
df_clean['transaction_velocity_missing'] = df_clean['transaction_velocity'].isnull().astype(int)
df_clean['amount_deviation_score_missing'] = df_clean['amount_deviation_score'].isnull().astype(int)

In [33]:
negative_time_count = (df_clean['time_since_last_txn_min'] < 0).sum()

negative_time_count

np.int64(8877)

In [34]:
df_clean['time_since_last_txn_negative_flag'] = (df_clean['time_since_last_txn_min'] < 0).astype(int)

In [35]:
df_clean.loc[df_clean['time_since_last_txn_min'] < 0, 'time_since_last_txn_min'] = np.nan

In [36]:
time_since_median = df_clean['time_since_last_txn_min'].median()

df_clean['time_since_last_txn_min'] = df_clean['time_since_last_txn_min'].fillna(time_since_median)

In [37]:
transaction_velocity_median = df_clean['transaction_velocity'].median()

df_clean['transaction_velocity'] = df_clean['transaction_velocity'].fillna(transaction_velocity_median)

In [38]:
amount_deviation_median = df_clean['amount_deviation_score'].median()

df_clean['amount_deviation_score'] = df_clean['amount_deviation_score'].fillna(amount_deviation_median)

In [39]:
df_clean.isnull().sum()

transaction_id                       0
user_id                              0
receiver_id                          0
receiver_type                        0
amount                               0
timestamp                            0
date                                 0
hour_of_day                          0
day_of_week                          0
is_weekend                           0
is_night_transaction                 0
time_since_last_txn_min              0
transaction_type                     0
payment_app                          0
device_type                          0
status                               0
user_city_tier                       0
user_kyc_status                      0
user_avg_monthly_txn                 0
user_avg_txn_value                   0
user_loyalty_score                   0
new_device_flag                      0
ip_location_mismatch                 0
failed_attempts_last_24h             0
transaction_velocity                 0
amount_deviation_score               0
is_fraud                             0
recurring_payment_flag               0
balance_after_transaction            0
transaction_frequency_score          0
time_since_last_txn_missing          0
transaction_velocity_missing         0
amount_deviation_score_missing       0
time_since_last_txn_negative_flag    0
dtype: int64

In [40]:
(df_clean['time_since_last_txn_min'] <0).sum()

np.int64(0)

In [41]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   transaction_id                     20000 non-null  str
 1   user_id                            20000 non-null  str
 2   receiver_id                        20000 non-null  str
 3   receiver_type                      20000 non-null  str
 4   amount                             20000 non-null  float64
 5   timestamp                          20000 non-null  datetime64[us]
 6   date                               20000 non-null  datetime64[us]
 7   hour_of_day                        20000 non-null  int64
 8   day_of_week                        20000 non-null  str
 9   is_weekend                         20000 non-null  int64
 10  is_night_transaction               20000 non-null  int64
 11  time_since_last_txn_min            20000 non-null  float64
 12  transaction_type                   20000 non-null  str
 13  payment_app                        20000 non-null  str
 14  device_type                        20000 non-null  str
 15  status                             20000 non-null  str
 16  user_city_tier                     20000 non-null  str
 17  user_kyc_status                    20000 non-null  str
 18  user_avg_monthly_txn               20000 non-null  int64
 19  user_avg_txn_value                 20000 non-null  float64
 20  user_loyalty_score                 20000 non-null  float64
 21  new_device_flag                    20000 non-null  int64
 22  ip_location_mismatch               20000 non-null  int64
 23  failed_attempts_last_24h           20000 non-null  int64
 24  transaction_velocity               20000 non-null  float64
 25  amount_deviation_score             20000 non-null  float64
 26  is_fraud                           20000 non-null  int64
 27  recurring_payment_flag             20000 non-null  int64
 28  balance_after_transaction          20000 non-null  float64
 29  transaction_frequency_score        20000 non-null  float64
 30  time_since_last_txn_missing        20000 non-null  int64
 31  transaction_velocity_missing       20000 non-null  int64
 32  amount_deviation_score_missing     20000 non-null  int64
 33  time_since_last_txn_negative_flag  20000 non-null  int64
dtypes: datetime64[us](2), float64(8), int64(13), str(11)
memory usage: 5.2 MB

In [42]:
df_clean.shape

(20000, 34)